config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :high_scores
  resources :todos

  resources :todos
  root 'todos#index'

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	validates :title, :notes, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        flash[:success] = 'Todo was successfully created.'
        format.html { redirect_to @todo }
        format.json { render :show, status: :created, location: @todo }
      else
        flash[:danger] = 'There was a problem creating the Todo.'
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        flash[:success] = 'Todo was successfully updated.'
        format.html { redirect_to @todo }
        format.json { render :show, status: :ok, location: @todo }
      else
        flash[:danger] = 'There was a problem updating the Todo.'
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      flash[:success] = 'Todo was successfully destroyed.'
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing High Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing High Scores</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
        <td><%= high_score.game %></td>
        <td><%= high_score.score %></td>
        <td><%= link_to 'Show', high_score %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New High Score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>TodoApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render 'navigation' %>

		<div id="main-container" class="container">
		
			<div class="row">
				<div class="col-xs-12">
					<% flash.each do |name, msg| %>
						<%= content_tag :div, msg, class: "alert alert-#{name}" %>
					<% end %>
				</div>
			</div>

		  <div class="row">
		    <div class="col-xs-3">
		      <h3>The Todo App</h3>
		    </div>
		    <div class="col-xs-9">
		      <%= yield %>
		    </div>
		  </div>

		</div>

	</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10"> 
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :notes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :notes, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/todos/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Cool Todo App</a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Login</a></li>
					<li class="divider"></li>
					<li><%= link_to 'Create a todo', new_todo_path %></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', todos_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" 
          title="<%= "Created on #{todo.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= todo.title %>
          </span>
        </td>
        <td>
          <% if todo.notes? %>
            <!-- Button trigger modal -->
            <button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= todo.id %>-notes">
              View notes
            </button>

            <!-- Modal -->
            <div class="modal fade" id="todo-<%= todo.id %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= todo.id %>-label" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="todo-<%= todo.id %>-label">Notes</h4>
                  </div>
                  <div class="modal-body">
                    <%= todo.notes %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

          <% if todo.notes? %>
            <button type="button" class="btn btn-link has-popover" data-toggle="popover" title="Notes" data-content="<%= todo.notes %>">View notes (popover)</button>
          <% end %>
          
        </td>
        <td><%= link_to 'Show', todo, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', todo, class: "btn btn-default btn-sm" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_todo_path, class: "btn btn-success" do %>
  <i class="glyphicon glyphicon-plus"></i> New Todo
<% end %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>